"""Decode SBPMEN.DAT - the thirty stages of Sokoban Select 30.

    python tools/men.py disk/SBPMEN.DAT          all thirty
    python tools/men.py disk/SBPMEN.DAT 11       one
    python tools/men.py disk/SBPMEN.DAT --c      as a C table

The file is 7798 bytes and looks empty at a glance: only 869 of those bytes are
non-zero.  That is because a stage is three bitmaps and floor is a clear bit,
so most of the file is floor.

The non-zero bytes fall into a strict 250-byte period, and inside one period
they sit at +0x0e, +0x5a and +0xb2 - which is 4 bytes into an array at +0x0a,
0 bytes into one at +0x5a and 8 bytes into one at +0xaa.  Three arrays of 20
uint32 (80 bytes each) after a 10-byte header comes to exactly 250:

    +0x00  1  tile size, 3 or 2; 2 is used by the seven widest boards
    +0x01  1  the man's starting column
    +0x02  1  the man's starting row
    +0x03  2  the target move count, little endian (stage 1 = 71, 26 = 2001)
    +0x05  5  zero
    +0x0a  80 goals    20 rows of 32 bits
    +0x5a  80 walls
    +0xaa  80 boxes

A row's bit 7 of its first byte is column 0 - the PC-98 VRAM order, the same
way round as the tile bitmaps - so the rows read as bytes straight off the
screen.  Reading them the other way round also puts nothing on a wall, because
the boards are nearly symmetric, but it mirrors every asymmetric one and moves
the man off the floor.

Record 0 is all zeros and records 1..30 are the stages, with a 48-byte tail on
the end.  Checks that all thirty pass: box count equals goal count, no box or
goal on a wall, and the man starts on floor.

Which plane is which comes from FUN_1edb_338f, the original's loader:

    code = 4 * plane0_bit + 2 * plane1_bit + 1 * plane2_bit
    board[col + row * 0x20] = DS:0xba[code]

with DS:0xba holding `00 02 01 09 03 04 09 09`.  FUN_1edb_2bb9 then redraws a
board value of 2 as one of fifteen sprites 0x1d..0x2b - the Kao product
packages - so code 1, which is plane2 alone, is a BOX, and code 4, plane0
alone, draws the blue dot and is a GOAL.  The counts are equal and both
readings give a legal puzzle, so only the sprite settles it.

The sibling name in the executable's filename table is `usermen.dat`, so MEN is
面 and this is the built-in stage set.  It is a plain file on the disk, not
packed and not inside SBP98.EXE, which is why a scan of the executable for
board-shaped data found nothing.
"""
import struct
import sys

REC = 250
TAIL = 48
ROWS = 20
COLS = 32
GOALS, WALLS, BOXES = 0, 1, 2


class Stage:
    def __init__(self, rec):
        self.tile = rec[0]
        self.sx = rec[1]
        self.sy = rec[2]
        self.moves, = struct.unpack_from('<H', rec, 3)
        self.plane = []
        for p in range(3):
            o = 10 + p * 80
            self.plane.append([int.from_bytes(rec[o + r * 4:o + r * 4 + 4],
                                              'big') for r in range(ROWS)])
        self.h = max((r for r in range(ROWS)
                      if any(p[r] for p in self.plane)), default=0) + 1
        self.w = max((COLS - 1 - (v & -v).bit_length() + 1
                      for p in self.plane for v in p if v), default=0) + 1

    def at(self, x, y):
        """(wall, box, goal) of one square."""
        if not (0 <= x < COLS and 0 <= y < ROWS):
            return 0, 0, 0
        m = 1 << (COLS - 1 - x)
        return tuple(1 if self.plane[p][y] & m else 0
                     for p in (WALLS, BOXES, GOALS))

    def count(self, p):
        return sum(bin(v).count('1') for v in self.plane[p])

    def art(self):
        out = []
        for y in range(self.h):
            s = ''
            for x in range(self.w):
                wall, box, goal = self.at(x, y)
                if (x, y) == (self.sx, self.sy):
                    s += '+' if goal else '@'
                elif wall:
                    s += '#'
                elif box:
                    s += '*' if goal else '$'
                else:
                    s += '.' if goal else ' '
            out.append(s)
        return out


def stages(data):
    for n in range(1, (len(data) - TAIL) // REC):
        yield n, Stage(data[n * REC:(n + 1) * REC])


def check(n, s):
    """Everything that must hold if the layout above is right."""
    bad = []
    if s.count(BOXES) != s.count(GOALS):
        bad.append('%d boxes but %d goals' % (s.count(BOXES), s.count(GOALS)))
    if s.at(s.sx, s.sy)[0]:
        bad.append('man starts on a wall')
    for y in range(ROWS):
        w = s.plane[WALLS][y]
        if s.plane[BOXES][y] & w:
            bad.append('box on a wall in row %d' % y)
        if s.plane[GOALS][y] & w:
            bad.append('goal on a wall in row %d' % y)
    return bad


def as_c(all_of):
    print('/* Generated by tools/men.py from SBPMEN.DAT.  Do not edit. */')
    print('const SokoStage sokoStages[SOKO_STAGES] = {')
    for n, s in all_of:
        print('    { %d, %2d, %2d, %4d, %2d, %2d,   /* stage %d */' %
              (s.tile, s.sx, s.sy, s.moves, s.w, s.h, n))
        for p, name in ((BOXES, 'boxes'), (WALLS, 'walls'), (GOALS, 'goals')):
            print('      { %s },  /* %s */' %
                  (', '.join('0x%08lxUL' % v for v in s.plane[p][:s.h]), name))
        print('    },')
    print('};')


def main():
    data = open(sys.argv[1], 'rb').read()
    arg = sys.argv[2] if len(sys.argv) > 2 else None
    all_of = list(stages(data))

    if arg == '--c':
        as_c(all_of)
        return

    want = int(arg) if arg else None
    print('%d bytes: %d records of %d, %d byte tail' %
          (len(data), len(all_of) + 1, REC, len(data) - TAIL - REC * (len(all_of) + 1) + TAIL))
    faults = 0
    for n, s in all_of:
        bad = check(n, s)
        faults += len(bad)
        if want is not None and n != want:
            continue
        print('%2d  %2dx%-2d tile=%d start=(%d,%d) boxes=%d moves=%d%s' %
              (n, s.w, s.h, s.tile, s.sx, s.sy, s.count(BOXES), s.moves,
               '  ** ' + '; '.join(bad) if bad else ''))
        for line in s.art():
            print('    |%s|' % line)
    print('%d stages, %d faults' % (len(all_of), faults))


if __name__ == '__main__':
    main()
